"""
Example Playwright test file generated by the test generator.
This is a sample template showing the expected format of generated tests.
"""

from playwright.async_api import async_playwright, expect


async def test_example_login_scenario():
    """
    Example test demonstrating the expected structure for generated Playwright tests.

    This template shows:
    - Async/await syntax with asyncio
    - Proper locator strategies (data-testid, CSS, text)
    - Explicit waits for dynamic content
    - Comprehensive assertions with error messages
    """
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Navigate to the application
        await page.goto("https://example-app.com/login")

        # Wait for page to be fully loaded
        await expect(page).to_have_url("https://example-app.com/login", timeout=10000)

        # Locate and fill login form
        email_field = page.locator('[data-testid="email-input"]')
        await expect(email_field).to_be_visible()
        await email_field.fill("testuser@example.com")

        password_field = page.locator('[data-testid="password-input"]')
        await expect(password_field).to_be_visible()
        await password_field.fill("securePassword123!")

        # Locate and click login button
        login_button = page.locator('[data-testid="login-button"]')
        await expect(login_button).to_be_enabled()
        await login_button.click()

        # Wait for navigation or dynamic content
        await page.wait_for_load_state("networkidle")

        # Verify successful login - check for user dashboard elements
        dashboard_heading = page.locator('[data-testid="dashboard-heading"]')
        await expect(dashboard_heading).to_be_visible(timeout=5000)

        # Verify user name is displayed
        user_greeting = page.locator('[data-testid="user-greeting"]')
        await expect(user_greeting).to_have_text("Welcome, testuser@example.com")

        # Cleanup
        await browser.close()
